services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: fitness
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  frontend-builder:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run build"

  app:
    build: 
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /app/vendor
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: fitness
      DB_USERNAME: root
      DB_PASSWORD: root
      GROQ_API_KEY: ${GROQ_API_KEY}


volumes:
  db_data: